pages:
  - page_name: st-vizzu (Streamlit-ipyvizzu)
    icon: ğŸˆ
    script_path: app.py
    layout: wide  # By default, layout is 'centered' for all pages. See all the default values in page_config.py
sections:
  - name: Examples â¤µï¸
    icon: ğŸ”¡
    pages:
      - page_name: Example 1 (Basic)  
        icon: ğŸ“Š
        script_path: pages/Basic-Demo.py
        layout: wide
      - page_name: Example 2 (Story)
        icon: ğŸ¥
        date_added: 2022-07-04  # If younger than 30 days, the page name will be augmented with a neat :new: emoji!
        script_path: pages/Story-Demo.py
        layout: wide
      - page_name: Example 3 (Bubble-Chart)  # Explicit naming here overwrites the name inferred from script_path
        icon: ğŸ’­
        script_path: pages/BubbleChart.py
        layout: wide
      - page_name : Example 4 (EDA)
        icon: ğŸ‘¨ğŸ¾â€ğŸ’»
        script_path: pages/Netflix-EDA.py
        layout: wide
      - page_name : Example 5 (Workarounds)
        icon: ğŸ€
        script_path: pages/Workarounds.py
        layout: wide

  - name: More Examples (Coming soon ...)
    icon: ğŸ”¢
    pages:
      - page_name: Example three
        icon: ğŸ¦‡
        visible: false
      - page_name: Old App
        icon: ğŸ’€
        visible: false  # This app will not appear in the menu!
